        #Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
        #1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        #By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

total = 2
fib1 = 1
fib2 = 2

while fib2 < 4000000:
    temp = fib2
    fib2 += fib1
    fib1 = temp
    if fib2 % 2 == 0:
        total += fib2

print(total)


# another approach from Euler
l = [1, 2]

while l[-1] <= 4000000:
    l.append( l[-1] + l[-2] )

print(sum(filter( lambda x: x%2==0, l )))
