using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using ProjectEuler;

namespace Euler.Test
{
    [TestClass]
    public class Problem2Tests
    {
        //Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
        //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        //By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

        [TestMethod]
        public void Problem2_Can_Solve()
        {
            // Arrange
            var expected = 4613732;
            var target = new Problem2();

            // Act
            var result = target.Solve();

            // Assert
            Assert.AreEqual(expected, result);
        }

        [TestMethod]
        public void Problem2_Can_Get10thFibTerm()
        {
            // Arrange
            var expected = 89;
            
            // Act
            var result = this.GetFibTerm(11);

            // Assert
            Assert.AreEqual(expected, result);
        }

        private int GetFibTerm(int term)
        {
            if (term == 1 || term == 2) return 1;
            else return GetFibTerm(term - 2) + GetFibTerm(term - 1); 
        }
    }
}
